# -*- coding: utf-8 -*-
"""lexicon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQpPSCpmBTml-8OiN4dHOKZ9n0lR2dYm
"""

import torch


print("GPU Available:", torch.cuda.is_available())


if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

!pip install datasets

from datasets import load_dataset



print("Downloading Karakalpak corpus...")

corpus_ds = load_dataset("bekan/karakalpak_corpus_v1_m")

print("Karakalpak corpus successfully downloaded.\n")


print("========== CORPUS STRUCTURE ==========")
print(corpus_ds)


print("\n========== CORPUS EXAMPLE ==========")
print(corpus_ds["train"][0])

import re
from collections import Counter



corpus_texts = corpus_ds["train"]["text"]



stopwords = set()

for item in stopwords_ds["train"]:
    stopwords.add(item["text"].strip().lower())



all_words = []

for text in corpus_texts:


    text = text.lower()


    words = re.findall(r"\b[a-záǵíńóqshúýәç]+\b", text)


    filtered_words = [
        word for word in words
        if word not in stopwords and len(word) > 2
    ]

    all_words.extend(filtered_words)



freq = Counter(all_words)



top100 = freq.most_common(100)



print("\nTOP 100 FULL WORDS:\n")

for i, (word, count) in enumerate(top100, 1):
    print(f"{i:3}. {word:<20} {count}")

import random
import pandas as pd



texts = corpus_ds["train"]["text"]



subset_1000 = random.sample(texts, 1000)

print("1000-sentence subset created successfully.\n")



print("========== SAMPLE SENTENCES ==========\n")

for i, sent in enumerate(subset_1000[:20], 1):

    print(f"{i}. {sent}\n")



empty_sentences = [s for s in subset_1000 if len(s.strip()) == 0]

print(f"\nEmpty sentences found: {len(empty_sentences)}")


short_sentences = [s for s in subset_1000 if len(s.split()) < 3]

print(f"Very short sentences (<3 words): {len(short_sentences)}")



df_subset = pd.DataFrame(subset_1000, columns=["text"])

print("\nSubset dataframe created successfully.")


df_subset.head()

!pip install stanza

import stanza


stanza.download('tr')


nlp = stanza.Pipeline('tr', processors='tokenize,pos')

text = "Men kitap oqıp atırman."

doc = nlp(text)

for sentence in doc.sentences:
    for word in sentence.words:
        print(word.text, word.upos)

import pandas as pd



LIMIT = 300

tagged_rows = []

print("Starting POS tagging...\n")



for sent_id, text in enumerate(subset_1000[:LIMIT]):


    doc = nlp(text)

    for sentence in doc.sentences:

        for word in sentence.words:

            tagged_rows.append({
                "sentence_id": sent_id,
                "word": word.text,
                "upos": word.upos
            })


    if sent_id % 50 == 0:
        print(f"Processed {sent_id} sentences")

print("\nPOS tagging completed.")



df_pos = pd.DataFrame(tagged_rows)



df_pos.to_csv("karakalpak_pos_tagged.csv", index=False)

print("\nFile saved successfully.")

import random
import re
import pandas as pd
import stanza


print("Downloading and initializing Stanza Turkish model...")
stanza.download("tr")
nlp = stanza.Pipeline("tr", processors="tokenize,pos")


sentences_300 = df_subset["text"].head(300).tolist()
print(f"Successfully loaded {len(sentences_300)} sentences for processing.\n")



def filter_karakalpak_pos(raw_tokens):
    """Applies specific Karakalpak grammar rules over Stanza's Turkish output."""
    merged_tokens = []
    skip_next = False


    for i in range(len(raw_tokens)):
        if skip_next:
            skip_next = False
            continue

        current = raw_tokens[i]

        if i + 1 < len(raw_tokens):
            next_t = raw_tokens[i + 1]

            if (
                next_t["token"] in ["ń", "ǵı", "te", "ti", "tı", "ni", "nı"]
                and current["sent_id"] == next_t["sent_id"]
            ):
                current["token"] = f"{current['token']}'{next_t['token']}"
                if current["pos"] in ["NUM", "VERB"]:
                    current["pos"] = "NOUN"
                skip_next = True

        merged_tokens.append(current)


    HARD_MAPPINGS = {
        "ushın": "ADP",
        "menen": "ADP",
        "hám": "CCONJ",
        "ol": "PRON",
        "olar": "PRON",
        "emes": "AUX",
        "edi": "AUX",
        "boldı": "VERB",
        "kerek": "ADJ",
    }

    for item in merged_tokens:
        token_lower = item["token"].lower()

        # Rule 1: Static dictionary overrides
        if token_lower in HARD_MAPPINGS:
            item["pos"] = HARD_MAPPINGS[token_lower]
            continue

        # Rule 2: Verbal nouns (gerunds) ending in -iw / -ıw plus case variations
        if re.search(r"[iı]w(ǵa|ge|dı|di|dan|den|lar)?$", token_lower):
            item["pos"] = "VERB"
            continue

        # Rule 3: Karakalpak Participles ending in -atuǵın, -etuǵın, -tuǵın
        if re.search(r"[ae]?tuǵın$", token_lower):
            item["pos"] = "VERB"
            continue

        # Rule 4: Past / continuous markers ending in -ǵan, -gen, -qan, -ken, -atır
        if re.search(r"(ǵan|gen|qan|ken|atır)$", token_lower) and item[
            "pos"
        ] in ["NUM", "NOUN"]:
            item["pos"] = "VERB"
            continue

    return merged_tokens



final_output_rows = []

print("Processing text through Stanza and applying filters... Please wait.")
for sent_idx, sentence_text in enumerate(sentences_300):

    if not sentence_text.strip():
        continue


    doc = nlp(sentence_text)


    raw_sentence_tokens = []
    for sentence in doc.sentences:
        for word in sentence.words:
            raw_sentence_tokens.append(
                {"sent_id": sent_idx, "token": word.text, "pos": word.upos}
            )


    clean_sentence_tokens = filter_karakalpak_pos(raw_sentence_tokens)


    final_output_rows.extend(clean_sentence_tokens)

print("Processing complete!\n")


print(f"{'Sent ID':<10}{'Token':<25}{'Corrected POS'}")
print("-" * 50)
for item in final_output_rows[:40]:
    print(f"{item['sent_id']:<10}{item['token']:<25}{item['pos']}")


df_output = pd.DataFrame(final_output_rows)
df_output.to_csv("karakalpak_filtered_pos.csv", index=False, sep="\t")

import stanza
import pandas as pd
import re
from tqdm import tqdm


nlp_kk = stanza.Pipeline("kk", processors="tokenize,pos")

def to_cyrillic(text):
    mapping = {'q': 'қ', 'ǵ': 'ғ', 'ń': 'ң', 'sh': 'ш', 'ch': 'ч', 'ı': 'і',
               'ó': 'ө', 'ú': 'ү', 'w': 'ў', 'a': 'а', 'b': 'б', 'd': 'д',
               'e': 'е', 'f': 'ф', 'g': 'г', 'h': 'һ', 'i': 'и', 'j': 'ж',
               'k': 'к', 'l': 'л', 'm': 'м', 'n': 'н', 'o': 'о', 'p': 'п',
               'r': 'р', 's': 'с', 't': 'т', 'u': 'у', 'v': 'в', 'y': 'й', 'z': 'з'}
    pattern = re.compile('|'.join(re.escape(k) for k in sorted(mapping.keys(), key=len, reverse=True)))
    return pattern.sub(lambda m: mapping[m.group(0)], text.lower())


final_results = []
subset_300 = df_subset["text"].head(300).tolist()

for sent_id, sentence in tqdm(enumerate(subset_300), total=300):
    cyr_sentence = to_cyrillic(sentence)
    doc = nlp_kk(cyr_sentence)


    word_seq = 0
    for sent in doc.sentences:
        for word in sent.words:
            final_results.append({
                "sent_id": sent_id,
                "word_seq": word_seq,
                "original_word": sentence.split()[word_seq] if word_seq < len(sentence.split()) else word.text,
                "cyrillic_word": word.text,
                "pos": word.upos
            })
            word_seq += 1

df_output = pd.DataFrame(final_results)
df_output.to_csv("final_tagged_data.txt", index=False, sep="\t")

print("\nProcess complete! Saved as 'final_tagged_data.txt'.")

def correct_pos(row):
    word = row['original_word'].lower()
    pos = row['pos']


    lookup = {
        'bul': 'PRON',
        'hám': 'CCONJ',
        'ushın': 'ADP',
        'bir': 'NUM',
        'bolıwı': 'VERB',
        'e': 'PART'
    }

    if word in lookup:
        return lookup[word]


    if not word.isalnum():
        return "PUNCT"


    if word.endswith(('li', 'lı')):
        return "ADJ"

    return pos


df['pos'] = df.apply(correct_pos, axis=1)


df.to_csv("corrected_tagged_data.txt", index=False, sep="\t")
files.download("corrected_tagged_data.txt")

